// Generated by CoffeeScript 1.3.1
(function() {
  var Emulator, args, debug, emu;

  Emulator = require('./emu').Emulator;

  /*
  # Loading and running the emulator
  */


  args = process.argv.splice(2);

  if (args.length === 0) {
    console.info("Usage: coffee emu.coffee filename");
  } else {
    debug = false;
    if (args[0] === "-d") {
      debug = true;
      args = args.splice(1);
    }
    emu = new Emulator({
      memSize: 500,
      debug: debug
    });
    emu.load(args[0], function() {
      var programParams;
      programParams = args.splice(1);
      if (!(programParams instanceof Array)) {
        programParams = [programParams];
      }
      return emu.execute(programParams, function(exitCode) {
        if (exitCode !== 0) {
          return console.info("Exit code is " + exitCode);
        } else {
          return console.info("Finished.");
        }
      });
    });
  }

}).call(this);
